version: "2"
services:
  application:
    build: .  # Build the Docker image from the current directory
    container_name: rest-app
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MONGO_DB_URL=${MONGO_DB_URL}
    volumes:
      - .:/app  # Optional: Mount the current directory into the container for local development (if needed)
    restart: always  # Automatically restart the container if it crashes
